[package]
  name = "wemo"
  version = "0.0.12"
  authors = [ "Brandon Thomas <bt@brand.io>", "Brandon Thomas <echelon@gmail.com>" ]
  description = "A library for interacting with Belkin WeMo home automation devices."
  keywords = [ "WeMo", "Belkin", "home", "automation", "UPNP" ]
  categories = [ "api-bindings" ]
  license = "BSD-4-Clause"
  readme = "README.md"
  repository = "https://github.com/echelon/wemo.rs"
  documentation = "https://docs.rs/wemo"

[lib]
  name = "wemo"
  path = "src/lib.rs"

[dependencies]
  get_if_addrs = { version = "0.4.*", optional = true } # TODO: Remove. GPL is too strict.
  iron = { version = "0.4.*", optional = true }
  lazy_static = "0.2.*"
  log = "0.3.*"
  mio = "0.5.*"
  persistent = { version = "0.2.*", optional = true }
  regex = "0.1.*"
  time = "0.1.*"
  url = "1.7.2"
  urlencoded = { version = "0.4.*", optional = true }

[features]
  # Optionally support subscribing to devices.
  default = ["subscriptions"]
  subscriptions = ["get_if_addrs", "iron", "persistent", "urlencoded"]

[dev-dependencies]
  eframe = "0.26.2"
  egui = "0.26.2"
